Happyr\EventTrackerBundle\Entity\Log:
  type: entity
  table: happyr_event_tracker
  repositoryClass: Happyr\EventTrackerBundle\Entity\LogRepository
  indexes:
    target_index:
      columns: [ target ]
    user_index:
      columns: [ user ]
    namespace_index:
      columns: [ namespace ]
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    target:
      type: string
      length: 255
    user:
      type: string
      length: 255
      nullable: true
    action:
      type: string
      length: 50
    namespace:
      type: string
      length: 50
    time:
      type: datetime
