Happyr\EventTrackerBundle\Entity\Log:
  type: entity
  table: happyr_event_tracker
  repositoryClass: Happyr\EventTrackerBundle\Entity\LogRepository
  indexes:
    target_index:
      columns: [ target ]
    namespace_index:
      columns: [ namespace ]
  manyToOne:
    user:
      targetEntity: Happyr\EventTrackerBundle\Entity\EventUserInterface
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    target:
      type: string
      length: 255
    action:
      type: string
      length: 50
    namespace:
      type: string
      length: 50
    time:
      type: datetime