parameters:

services:
  happyr.event_tracker.event_listener: '@Happyr\EventTrackerBundle\Service\EventListener'
  Happyr\EventTrackerBundle\Service\EventListener:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.token_storage'
      - []

  happyr.event_tracker.manager.aggressive: '@Happyr\EventTrackerBundle\Manager\AggressiveDatabaseManager'
  Happyr\EventTrackerBundle\Manager\AggressiveDatabaseManager:
    arguments:
      - '@doctrine.orm.entity_manager'

  happyr.event_tracker.manager.database: '@Happyr\EventTrackerBundle\Manager\DatabaseManager'
  Happyr\EventTrackerBundle\Manager\DatabaseManager:
    arguments:
      - '@doctrine.orm.entity_manager'

  happyr.event_tracker.twig: '@Happyr\EventTrackerBundle\Twig\EventTrackerExtension'
  Happyr\EventTrackerBundle\Twig\EventTrackerExtension:
    arguments: [ '@Happyr\EventTrackerBundle\Manager\EventTrackerManagerInterface' ]
    tags:
      - { name: twig.extension }
